package com.ghazitrader.ghazimart.utils;

public class ActionName {
    public final static String REGISTER_ADMIN = "RegisterAdmin";
    public final static String ALL_ADMIN = "AllAdmin";
    public final static String PARENT_ADMIN = "ParentAdmin";
    public final static String UPDATE_ADMIN = "UpdateAdmin";
    public final static String REGISTER_CATEGORY = "RegisterCategory";
    public final static String REGISTER_SUB_CATEGORY = "RegisterSubCategory";
    public final static String ALL_CATEGORY = "AllCategory";
    public final static String ALL_SUB_CATEGORY = "AllSubCategory";
    public final static String ADMIN_STATUS = "AdminStatus";
    public final static String CATEGORY_SUB_CATEGORY = "SubCategoryOfCategory";
    public final static String CATEGORY_STATUS = "CategoryStatus";
    public final static String SUB_CATEGORY_STATUS = "SubCategoryStatus";
    public final static String CATEGORY_PRODUCT = "CategoryProduct";
    public final static String USER_PRODUCT = "UserProduct";
    public final static String SAVE_PRODUCT = "SaveProduct";
    public final static String SAVE_PRODUCT_VALUE = "SaveProductValue";
    public final static String PRODUCT_VALUE = "ProductValue";
    public final static String ADMIN_LOGIN = "AdminLogin";
    public final static String ADD_FAVOURITE = "AddFavourite";
    public final static String CUSTOMER_FAVOURITE = "CustomerFavourite";
    public final static String CUSTOMER_REGISTER = "CustomerRegister";
    public final static String SAVE_ORDER = "SaveOrder";
    public final static String HOME_SCREEN = "HomeScreen";
    public final static String PRODUCT_VERIFY = "ProductVerify";
    public final static String SUB_CAT_IDS = "SubCatIds";
    public final static String UN_VERIFY_PRODUCTS = "UnVerifyProducts";
    public final static String VERIFY_PRODUCT = "VerifyProduct";
    public final static String OFFER_PRODUCTS = "OfferProducts";
    public final static String SAVE_OFFER_PRODUCT = "SaveOfferProducts";
    public final static String DELETE_OFFER_PRODUCT = "DeleteOfferProducts";
    public final static String SLIDE_OFFER = "SlideOffer";
    public final static String DELETE_SLIDE_OFFER = "DeleteSlideOffer";
    public final static String SAVE_STORE_ADDRESS = "SaveStoreAddress";
    public final static String STORE_ADDRESS_MOBILE = "StoreAddressByMobileNo";
    public final static String STORE_ADDRESS_NAME = "StoreAddressByCustName";
    public final static String HOME_SCREEN_PRODUCT_LIST = "HomeScreenProductList";
    public final static String SAVE_TEMP_PRODUCT = "SaveTempProduct";
    public final static String LIST_TEMP_PRODUCT = "ListTempProduct";
    public final static String SAVE_TEMP_ORDER = "SaveTempOrder";
    public final static String LIST_TEMP_ORDER = "ListTempOrder";
    public final static String CUSTOMER_ADDRESS_SAVE = "CustomerAddresSave";
    public final static String GET_CUSTOMER_ADDRESS = "CustomerAddress";
    public final static String CUSTOMER_ORDER = "CustomerOder";
    public final static String PRICE_SAVE = "priceSave";
    public final static String PRODUCT_PRICE_LIST = "productPriceList";
    public final static String SENT_OTP = "SendOTP";
    public final static String VERYFY_OTP = "VerifyOTP";
    public final static String PRODUCT_SEARCH = "ProductSearch";
    public final static String ADD_TO_CART = "AddToCard";
    public final static String CART_ITEMS = "CartItems";
    public final static String REMOVE_CART_ITEM = "RemoveCartItem";

}
